project.places =
    [
        {
            "id": 1,
            "image": "",
            "latitude": "92.7",
            "longitude": "Suno Sunao, Life Banao!",
            "name": "0xffa11431",
            "short_name": "",
        },
        {
            "id": 1,
            "image": "",
            "latitude": "92.7",
            "longitude": "Suno Sunao, Life Banao!",
            "name": "0xffa11431",
            "short_name": "",
        },
        {
            "id": 1,
            "image": "",
            "latitude": "92.7",
            "longitude": "Suno Sunao, Life Banao!",
            "name": "0xffa11431",
            "short_name": "",
        },
        {
            "id": 1,
            "image": "",
            "latitude": "92.7",
            "longitude": "Suno Sunao, Life Banao!",
            "name": "0xffa11431",
            "short_name": "",
        },
        {
            "id": 1,
            "image": "",
            "latitude": "92.7",
            "longitude": "Suno Sunao, Life Banao!",
            "name": "0xffa11431",
            "short_name": "",
        },
        {
            "id": 1,
            "image": "",
            "latitude": "92.7",
            "longitude": "Suno Sunao, Life Banao!",
            "name": "0xffa11431",
            "short_name": "",
        },
        {
            "id": 1,
            "image": "",
            "latitude": "92.7",
            "longitude": "Suno Sunao, Life Banao!",
            "name": "0xffa11431",
            "short_name": "",
        },
        {
            "id": 1,
            "image": "",
            "latitude": "92.7",
            "longitude": "Suno Sunao, Life Banao!",
            "name": "0xffa11431",
            "short_name": "",
        },
        {
            "id": 1,
            "image": "",
            "latitude": "92.7",
            "longitude": "Suno Sunao, Life Banao!",
            "name": "0xffa11431",
            "short_name": "",
        }
    ];
